#!/bin/bash

for config in `ls home`
do
  if [ ! -e "$HOME/.$config" ]; then
    echo "symlinking $config"
    ln -s "`pwd`/home/$config" "$HOME/.$config"
  else
    echo "$config already symlinked"
  fi
done
