# locale vars

export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=$LANG

# Set editor
export EDITOR="vim"

unsetopt correct_all

setopt nohup
setopt nobeep
setopt extendedglob
setopt NOBGNICE
setopt autocd
setopt autopushd

source ~/.zsh/aliases.zsh
source ~/.zsh/env.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/key-bindings.zsh
source ~/.zsh/history.zsh
source ~/.zsh/git.zsh
source ~/.zsh/prompt.zsh

# Load tmuxinator
[[ -s ~/.tmuxinator/scripts/tmuxinator ]] && source ~/.tmuxinator/scripts/tmuxinator

# Load local zsh settings
source ~/.zshrc.local

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Set PATH to prioritize bin in current dir
[[ -d ./bin ]] && export PATH="./bin:$PATH"

